# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

automatically-unhide-macos-hidden-apps = true

# Startup Commands
# ---------------
after-login-command = []

# Layout Settings
# --------------

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Modify your focus callbacks to be more mouse-aware
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
# Window / Monitor Focus (ctrl-alt + arrows)
ctrl-alt-left = 'focus left --boundaries all-monitors-outer-frame'
ctrl-alt-right = 'focus right --boundaries all-monitors-outer-frame'
ctrl-alt-up = 'focus up --boundaries all-monitors-outer-frame'
ctrl-alt-down = 'focus down --boundaries all-monitors-outer-frame'
ctrl-alt-tab = 'focus-monitor --wrap-around next'
ctrl-alt-shift-tab = 'focus-monitor --wrap-around prev'

# Window Movement (ctrl-alt-shift + arrows)
ctrl-alt-shift-left = ['move left']
ctrl-alt-shift-right = ['move right']
ctrl-alt-shift-up = ['move up']
ctrl-alt-shift-down = ['move down']
ctrl-alt-shift-cmd-left = [
    'move-node-to-monitor left',
    'focus-monitor left',
    'move-mouse monitor-lazy-center'
]

# Move window right within monitor or to right monitor if at boundary
alt-shift-right = [
    'move right',
    'move-node-to-monitor right',
    'focus-monitor right',
    'move-mouse monitor-lazy-center'
]

# Resize Windows (ctrl-alt-shift + hjkl)
shift-alt-h = 'resize width -50'    # Shrink width
shift-alt-l = 'resize width +50'    # Grow width
shift-alt-k = 'resize height -50'   # Shrink height
shift-alt-j = 'resize height +50'   # Grow height

# Layout Controls
ctrl-alt-slash = 'layout tiles horizontal vertical'    # Tile layout
ctrl-alt-comma = 'layout accordion horizontal vertical' # Accordion layout
ctrl-cmd-f = 'fullscreen'                         # Toggle fullscreen   

# Workspace Navigation
alt-tab = 'workspace-back-and-forth'         # Toggle last workspace
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'                     # Enter workspace mode
ctrl-alt-cmd-up = 'workspace prev'                # Previous workspace
ctrl-alt-cmd-down = 'workspace next'              # Next workspace
 
# Join Windows (ctrl-shift-cmd + arrows)
ctrl-shift-cmd-left = ['join-with left']
ctrl-shift-cmd-right = ['join-with right']
ctrl-shift-cmd-up = ['join-with up']
ctrl-shift-cmd-down = ['join-with down']

# Quick Workspace Switching
alt-s = ['workspace S1']
alt-1 = ['workspace 1']
alt-2 = ['workspace 2']
alt-3 = ['workspace 3'] 
alt-4 = ['workspace 4']
alt-5 = ['workspace 5']
alt-6 = ['workspace 6']
#ctrl-alt-4 = ['workspace 4']
#ctrl-alt-5 = ['workspace 5']
#ctrl-alt-6 = ['workspace 6']
#ctrl-alt-7 = ['workspace 7']
#ctrl-alt-8 = ['workspace 8']
#ctrl-alt-9 = ['workspace 9']

#ctrl-alt-i = ['workspace I']
#ctrl-alt-b = ['workspace B']
#ctrl-alt-c = ['workspace C']


# Move Windows to Workspaces
alt-shift-s = ['move-node-to-workspace S1', 'workspace S1']
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
# Mode Switching
ctrl-alt-space = 'mode service'  # Enter service mode
ctrl-alt-w = 'mode workspace'

[mode.workspace.binding]
s = ['mode secondary']
t = ['mode temp']
1 = ['workspace 1','mode main']
2 = ['workspace 2','mode main']
3 = ['workspace 3','mode main']
4 = ['workspace 4','mode main']
5 = ['workspace 5','mode main']
6 = ['workspace 6','mode main']
shift-1 = ['move-node-to-workspace 1','workspace 1','mode main']
shift-2 = ['move-node-to-workspace 2','workspace 2','mode main']
shift-3 = ['move-node-to-workspace 3','workspace 3','mode main']
shift-4 = ['move-node-to-workspace 4','workspace 4','mode main']
shift-5 = ['move-node-to-workspace 5','workspace 5','mode main']
shift-6 = ['move-node-to-workspace 6','workspace 6','mode main']
esc = ['mode main']

[mode.secondary.binding]
1 = ['workspace S1','mode main']
2 = ['workspace S2','mode main']
3 = ['workspace S3','mode main']
shift-1 = ['move-node-to-workspace S1','workspace S1','mode main']
shift-2 = ['move-node-to-workspace S2','workspace S2','mode main']
shift-3 = ['move-node-to-workspace S3','workspace S3','mode main']
esc = ['mode main']

[mode.temp.binding]
1 = ['workspace TEMP1','mode main']
2 = ['workspace TEMP2','mode main']
3 = ['workspace TEMP3','mode main']
shift-1 = ['move-node-to-workspace TEMP1','workspace TEMP1','mode main']
shift-2 = ['move-node-to-workspace TEMP2','workspace TEMP2','mode main']
shift-3 = ['move-node-to-workspace TEMP3','workspace TEMP3','mode main']
esc = ['mode main']

# Launch Applications
# ctrl-alt-return = '''exec-and-forget osascript -e '
#     tell application "Terminal"
#         do script
#         activate
#     end tell'
# '''

#alt = ['workspace 1', 'mode main']

alt-n = 'exec-and-forget /Users/lars/.dotfiles/bin/create_workspace.sh'


#alt-d = ['move-all-nodes-to-workspace 1', 'workspace 1']

#alt-shift-1 = ['move-all-nodes-to-workspace 1', 'workspace 1']
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-space = 'mode service'

# Change workspace mode trigger to ctrl-alt-w
ctrl-alt-w = 'mode workspace'

ctrl-alt-1 = ['workspace 1']
ctrl-alt-2 = ['workspace 2']
ctrl-alt-3 = ['workspace 3']
ctrl-alt-4 = ['workspace 4']
ctrl-alt-5 = ['workspace 5']
ctrl-alt-6 = ['workspace 6']
ctrl-alt-7 = ['workspace 7']
ctrl-alt-8 = ['workspace 8']
ctrl-alt-9 = ['workspace 9']
ctrl-alt-b = ['workspace b']

ctrl-alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
ctrl-alt-shift-b = ['move-node-to-workspace b', 'workspace b']


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config','exec-and-forget borders', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layoutZ
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

left = ['join-with left', 'mode main']
down = ['join-with down', 'mode main']
up = ['join-with up', 'mode main']
right = ['join-with right', 'mode main']

# [workspace-to-monitor-force-assignment]
# 1oo = 1
# 2oo = 1
# 3oo = 1
# 4oo = 1
# 5oo = 1
# 6oo = 1
# 7oo = 1
# 8oo = 1
# 9oo = 1
# o1o = 2
# o2o = 2
# o3o = 2
# o4o = 2
# o5o = 2
# o6o = 2
# o7o = 2
# o8o = 2
# o9o = 2
# oo1 = 3
# oo2 = 3
# oo3 = 3
# oo4 = 3
# oo5 = 3
# oo6 = 3
# oo7 = 3
# oo8 = 3
# oo9 = 3

[[on-window-detected]]
if.app-id = 'org.tabby'
run = 'layout floating'

[workspace-to-monitor-force-assignment]
1 = 'main'      # Assigns workspace 1 to your main monitor (with menu bar)
2 = 'main'      # Assigns workspace 1 to your main monitor (with menu bar)
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'main'
TEMP1 = 'main'
TEMP2 = 'main'
TEMP3 = 'main'
S1 = 'secondary' # Assigns workspace 5 to your secondary monitor
S2 = 'secondary'
S3 = 'secondary'
