live_config_reload = true

[colors]
primary = { background = "#0d0f18", foreground = "#fffaf3" }
cursor = { text = "#ff0000", cursor = "#ffffff" }
selection = { text = "#ffffff", background = "#4e5a65" }
#draw_bold_text_with_bright_colors = true

[colors.normal]
black = "#222222"
red = "#ff000f"
green = "#8ce00a"
yellow = "#ffb900"
blue = "#008df8"
magenta = "#E45FE4"
cyan = "#00d7eb"
white = "#ffffff"

[colors.bright]
black = "#222222"
red = "#ff000f"
green = "#8ce00a"
yellow = "#ffb900"
blue = "#008df8"
magenta = "#E45FE4"
cyan = "#00d7eb"
white = "#ffffff"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[window]
decorations = "buttonless"
opacity = 0.8
blur = true
padding = { x = 5, y = 5 }

[keyboard]
[[keyboard.bindings]]
key = "V"
mods = "Control|Super"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi"
action = "ToggleViMode"
